<!-- urbverde-ui/src/components/modal/modalLayerInfo.vue -->
<template>
  <teleport to="body">
    <modalBootstrap
      ref="refModal"
      modalId="modalLayerInfo"
      :title="layerTitle"
      bodyText=""
      showSecondaryButton="true"
      primaryButtonText="Ok"
      secondaryButtonText="Ler mais"
      :primaryButtonClosesModal="true"
      :secondaryButtonClosesModal="false"
      @closeSecondary="openLayerInfoPage"
      @closePrimary="closeModal"
      class="layer-info-modal"
      size="lg"
    >
      <template #body>
        <div class="layer-info-content body-normal-regular" v-html="layerDescription">

        </div>
      </template>
    </modalBootstrap>
  </teleport>
</template>

<script setup>
import { ref, computed } from 'vue';
import modalBootstrap from './modalBootstrap.vue';
import { useLocationStore } from '@/stores/locationStore';

const refModal = ref(null);
const locationStore = useLocationStore();

const currentLayer = computed(() => locationStore.currentLayerName || '');

// Título do modal baseado na camada atual
const layerTitle = computed(() => `Informações sobre: ${currentLayer.value}`);

// Descrição da camada para o modal
const layerDescription = computed(() => {

  // Objeto com textos específicos para cada camada
  const layerDescriptions = {
    // Clima
    'Temperatura de superfície': '<p>A <strong>Temperatura de Superfície Terrestre</strong> é a temperatura estimada da superfície do solo, medida por imagens de satélite. Ela ajuda a monitorar o ambiente e a planejar áreas urbanas, permitindo a análise de ilhas de calor e padrões térmicos.<p><strong>Resolução:</strong> cada quadrado representa uma área de 30 x 30 metros.</p><p><strong>Metodologia:</strong> A TST é calculada a partir de imagens quinzenais do satélite <em>Landsat-8</em>, formando conjuntos de imagens anuais. O processo inclui a conversão dos valores digitais das imagens em radiância, aplicação da equação de Planck para obter temperaturas em Kelvin (K), que são convertidas para graus Celsius (°C). Uma correção atmosférica é aplicada usando um modelo de regressão linear baseado na relação entre temperatura de brilho e emissividade, conforme descrito por Ermida (2020).</p><p><strong>Cuidados ao analisar os dados:</strong> A TST pode ser influenciada por diferentes materiais de superfície, como asfalto, concreto e vegetação. A precisão dos dados está sujeita a fatores como cobertura de nuvens e variações atmosféricas. As temperaturas de superfície são representativas e úteis para mapear ilhas de calor urbanas, mas seus valores absolutos podem diferir de medições pontuais de temperatura do ar ou de superfícies específicas. Por isso, são analisadas as temperaturas relativas em relação à média urbana do município, destacando áreas com temperatura acima (ilhas de calor) ou abaixo da média (ilhas de frescor) e a intensidade desses fenômenos.</p><p><strong>Fonte:</strong> ERMIDA, S. L. et al. "Google Earth Engine open-source code for Land Surface Temperature estimation from the Landsat series". Remote Sensing, v. 12, n. 9, p. 1471, 2020. Disponível: <a href="https://doi.org/10.3390/rs12091471">aqui</a>.',
    'Temperatura máxima de superfície':'<p>A <strong>Temperatura Máxima de Superfície</strong> representa o maior valor registrado anualmente para cada setor censitário urbano, ao longo do período de 2016 a 2021. Esse dado é essencial para identificar as regiões mais afetadas por ondas de calor e compreender como diferentes áreas urbanas respondem às variações térmicas.</p> <p><strong>Resolução:</strong> Não se aplica.</p> <p><strong>Metodologia:</strong> A temperatura máxima é extraída a partir das imagens quinzenais do satélite <em>Landsat-8</em>, processadas em mosaicos anuais. O cálculo envolve a conversão dos valores digitais das imagens em temperatura, utilizando a equação de Planck. Para garantir precisão, aplica-se um modelo de correção atmosférica baseado na relação entre temperatura de brilho e emissividade.</p> <p><strong>Cuidados ao analisar os dados:</strong> A Temperatura Máxima de Superfície pode ser influenciada por diferentes coberturas do solo, como concreto, asfalto e vegetação. Além disso, fatores como cobertura de nuvens e variações atmosféricas podem afetar a captação dos dados. Como os valores representam a temperatura da superfície e não do ar, são analisadas as temperaturas relativas dentro do município, destacando as áreas mais quentes (ilhas de calor) e as mais frescas.</p> <p><strong>Fonte:</strong> ERMIDA, S. L. et al. "Google Earth Engine open-source code for Land Surface Temperature estimation from the Landsat series". Remote Sensing, v. 12, n. 9, p. 1471, 2020. Disponível: <a href="https://doi.org/10.3390/rs12091471">aqui</a>.</p>',
    'Nível de exposição à ilha de calor':'<p>O <strong>Coeficiente de Ilha de Calor</strong> mede a intensidade da ilha de calor urbana considerando a vulnerabilidade populacional. Esse índice ajuda a identificar áreas críticas onde idosos e crianças estão mais expostos a altas temperaturas.</p> <p><strong>Resolução:</strong> O coeficiente combina dois tipos de dados:</p> <ul> <li><strong>Temperatura de Superfície Terrestre (TST):</strong> resolução de 30 metros, com base nas imagens térmicas do <em>Landsat-8</em>.</li> <li><strong>Dados populacionais:</strong> extraídos do Censo do IBGE, organizados por setores censitários.</li> </ul> <p><strong>Metodologia:</strong> O coeficiente é calculado com base na TST e na população vulnerável do setor censitário, seguindo os passos:</p> <ul> <li>Identificação da <strong>temperatura de superfície terrestre</strong> (TST) a partir das imagens do <em>Landsat-8</em>.</li> <li>Cálculo da <strong>intensidade térmica</strong> do setor, comparando sua temperatura com a média da cidade.</li> <li>Obtenção dos <strong>dados populacionais</strong> do Censo do IBGE, considerando idosos e crianças como grupos vulneráveis.</li> <li>Multiplicação da população vulnerável pelo fator de intensidade térmica, gerando o <strong>Coeficiente de Ilha de Calor</strong>.</li> </ul> <p><strong>Cuidados ao analisar os dados:</strong></p> <ul> <li>A estimativa da população vulnerável depende dos dados censitários do IBGE, que podem sofrer defasagens entre censos.</li> <li>A precisão do coeficiente está ligada à resolução térmica do <em>Landsat-8</em> e à divisão dos setores censitários.</li> </ul> <p><strong>Fontes:</strong> </p> <ul> <li>Instituto Brasileiro de Geografia e Estatística (IBGE). <a href="https://censo2022.ibge.gov.br/panorama/downloads.html?localidade=BR">Censo Demográfico 2022</a>.</li> <li>NASA. <a href="https://landsat.gsfc.nasa.gov/landsat-8/landsat-8-data-users-handbook">Landsat 8 Science Data Users Handbook</a>.</li> <li>ERMIDA, S. L. <a href="https://doi.org/10.3390/rs12091471">Google Earth Engine Open-Source Code for Land Surface Temperature Estimation from the Landsat Series</a>. Remote Sensing, 2020.</li> </ul>',

    // Vegetação
    'Cobertura vegetal (PCV)': '<p>O <strong>Percentual de Cobertura vegetal (PCV)</strong> é uma estimativa da área de uma região que é coberta por vegetação, usando imagens de satélite.</p><p><strong>Resolução:</strong> cada quadrado representa uma área de 30 x 30 metros.</p> <p><strong>Metodologia:</strong> Para calcular o percentual, utilizamos o Modelo Linear de Mistura Espectral. Esse modelo analisa cada <em>pixel</em> das imagens de satélite, considerando frações de vegetação, solo e sombra. Os dados são obtidos a partir de um conjunto de imagens anual sem nuvens do satélite <em>Landsat-8</em>. Em seguida, os resultados são agrupados por setores censitários e municípios.</p> <p><strong>Cuidados ao analisar os dados:</strong> Como o PCV é uma estimativa baseada no Modelo Linear de Mistura Espectral, pode haver confusão entre as frações de sombra e vegetação, especialmente em áreas com alta densidade de árvores. Além disso, pode ocorrer confusão entre diferentes tipos de vegetação, como árvores, arbustos e gramados em algumas regiões.</p> <p><strong>Fonte:</strong> SMALL, C.; MILESI, C. Multi-scale standardized spectral mixture models. Remote Sensing Of Environment, Amsterdã, v. 136, p. 442–54, 19 jan. 2013. Disponível : <a href="https://doi.org/10.1016/j.rse.2013.05.024">aqui</a>.</p>',
    'Desigualdade sociambiental (IDSA)': '<p>O <strong>Indicador de Desigualdade Socioambiental (IDSA)</strong> mede as diferenças entre áreas de uma cidade em relação a condições como infraestrutura, aspectos sociais, densidade populacional e meio ambiente. Quanto mais próximo de 0, menor a desigualdade; quanto mais próximo de 1, maior a desigualdade na região. Esse indicador ajuda a entender quais áreas precisam de mais atenção para melhorar as condições de vida da população.</p> <p><strong>Resolução:</strong> Não se aplica.</p> <p><strong>Metodologia:</strong> O IDSA é composto por quatro subindicadores: Infraestrutura (Isi), Social (ISs), Demográfico (ISd) e Ambiental (ISa). Esses subindicadores são combinados para formar um indicador global que mede as desigualdades demográficas, sociais e ambientais. Valores próximos a 0 indicam menor desigualdade, enquanto valores próximos a 1 revelam maior desigualdade em determinada área.</p> <p><strong>Cuidados ao analisar os dados:</strong> Por se tratar de um dado que depende de informações censitárias, sua atualização está vinculada à realização de futuros Censos. Além disso, é importante considerar que o IDSA é uma medida relativa e deve ser analisada em conjunto com outros indicadores para uma compreensão mais completa das desigualdades socioambientais.</p> <p><strong>Fonte:</strong> Toppa, R. H.; Martines, M. R. Análise ambiental de áreas de interesse para o estabelecimento de unidades de conservação para a proteção dos mananciais do município de Araçoiaba da Serra, Estado de São Paulo. São Paulo, SP: Ed. dos autores, 2021.</p>',
    'Cobertura vegetal por pixel': '<p>A <strong>Cobertura vegetal por satélite</strong> é uma estimativa da área de uma região que é coberta por vegetação, usando imagens de satélite.</p><p><strong>Resolução:</strong> cada quadrado representa uma área de 30 x 30 metros.</p> <p><strong>Metodologia:</strong> Para calcular o percentual, utilizamos o Modelo Linear de Mistura Espectral. Esse modelo analisa cada <em>pixel</em> das imagens de satélite, considerando frações de vegetação, solo e sombra. Os dados são obtidos a partir de um conjunto de imagens anual sem nuvens do satélite <em>Landsat-8</em>.</p> <p><strong>Cuidados ao analisar os dados:</strong> Como o PCV é uma estimativa baseada no Modelo Linear de Mistura Espectral, pode haver confusão entre as frações de sombra e vegetação, especialmente em áreas com alta densidade de árvores. Além disso, pode ocorrer confusão entre diferentes tipos de vegetação, como árvores, arbustos e gramados em algumas regiões.</p> <p><strong>Fonte:</strong> SMALL, C.; MILESI, C. Multi-scale standardized spectral mixture models. Remote Sensing Of Environment, Amsterdã, v. 136, p. 442–54, 19 jan. 2013. Disponível : <a href="https://doi.org/10.1016/j.rse.2013.05.024">aqui</a>.</p>',
    'Vigor da vegetação (NDVI)': '<p>O <strong>Índice de Vegetação por Diferença Normalizada (NDVI)</strong> é amplamente utilizado para monitorar a densidade e a saúde da vegetação por meio de imagens de satélite. Ele permite identificar a produção primária de clorofila e umidade das plantas.</p> <p><strong>Resolução:</strong> cada quadrado representa uma área de 10 x 10 metros.</p> <p><strong>Metodologia:</strong> O NDVI é calculado a partir de um conjunto de imagens anual sem nuvens, construído com imagens do satélite <em>Sentinel-2</em>. A fórmula utiliza a diferença normalizada entre as bandas do infravermelho próximo e do vermelho.</p> <p><strong>Fonte:</strong> Rouse, J.W., Jr.; Haas, R.H.; Schell, J.; Deering, D. Monitoring the Vernal Advancement and Retrogradation (Green Wave Effect) of Natural Vegetation; Technical Report; 1973. Disponível: <a href="https://ntrs.nasa.gov/citations/19740022555">aqui</a>.</p>',
    'Cobertura vegetal por habitante (ICV)': '<p>O <strong>Índice de Cobertura Vegetal (ICV)</strong> representa a divisão da área coberta por vegetação pela área total de uma determinada região, permitindo estimar a quantidade de vegetação disponível para cada habitante dessa região.</p> <p><strong>Resolução:</strong> depende do recorte visual escolhido.</p> <p><strong>Metodologia:</strong> A partir dos dados de Percentual de Cobertura Vegetal (PCV), calcula-se a área vegetada do polígono. Em seguida, utilizando os dados do Censo, determina-se o ICV para cada setor censitário e município.</p> <p><strong>Cuidados ao analisar os dados:</strong> Como o ICV depende de informações censitárias, sua atualização está vinculada à realização de futuros Censos.</p>',
    'Impermeabilização do solo (PSI)': '<p>A <strong>Impermeabilização do Solo</strong> representa o percentual da superfície urbana que está coberta por materiais impermeáveis, como concreto e asfalto, impedindo a infiltração de água no solo. Esse dado é essencial para avaliar riscos de alagamento, sobrecarga da drenagem urbana e impacto ambiental.</p> <p><strong>Resolução:</strong> Não se aplica (dado vetorial por setor censitário).</p> <p><strong>Metodologia:</strong> Utilizando imagens de satélite do <em>Landsat-8</em>, aplicou-se o Modelo Linear de Mistura Espectral (MLME) para estimar as frações de cobertura da superfície. Em seguida, um algoritmo de <em>Random Forest</em> foi treinado para classificar os setores censitários quanto ao grau de impermeabilização, com base nas frações de solo exposto e materiais artificiais.</p> <p><strong>Cuidados ao analisar os dados:</strong> A acurácia do dado depende da qualidade das imagens de satélite e da capacidade do modelo de distinguir superfícies com características semelhantes, como telhados e solo seco. Quanto menor o valor, melhor para a drenagem e o equilíbrio ambiental urbano.</p> <p><strong>Fonte:</strong> Equipe UrbVerde com base em dados do <em>Landsat-8</em> e processamento no Google Earth Engine.</p>',

    // Parques e praças
    'Distância media até as praças': '<p>A <strong>Distância média até as praças</strong> indica o quanto os moradores precisam caminhar para encontrar uma praça ou parque. Esse dado permite compreender melhor quais regiões do município têm maior ou menor facilidade de acesso a espaços livres.</p><p><strong>Resolução:</strong> Não se aplica.</p><p><strong>Metodologia:</strong> A distância média é calculada como a média aritmética das distâncias entre os centróides dos setores censitários urbanos e as áreas verdes mapeadas.</p><p><strong>Cuidados ao analisar os dados:</strong> A precisão do indicador depende da atualização dos dados censitários e da qualidade do mapeamento das áreas verdes.</p><p><strong>Fontes:</strong> PIPAE. <em>Relatório Metodológico</em>. UrbVerde. <a href="https://www.livrosabertos.abcd.usp.br/portaldelivrosUSP/catalog/book/1281">Livro da UrbVerde</a>.</p>',
    'Distância media até as praças (>5000m²)': '<p>A <strong>Distância média até as praças com áreas maiores de 5000 metros quadrados</strong> indica o quanto os moradores precisam caminhar para encontrar uma praça ou parque maior de 5000 metros quadrados. Esse dado permite compreender melhor quais regiões do município têm maior ou menor facilidade de acesso a espaços livres.</p><p><strong>Resolução:</strong> Não se aplica.</p><p><strong>Metodologia:</strong> A distância média é calculada como a média aritmética das distâncias entre os centróides dos setores censitários urbanos e as áreas verdes mapeadas (dada a situação de 5000 metros quadrados).</p><p><strong>Cuidados ao analisar os dados:</strong> A precisão do indicador depende da atualização dos dados censitários e da qualidade do mapeamento das áreas verdes.</p><p><strong>Fontes:</strong> PIPAE. <em>Relatório Metodológico</em>. UrbVerde. <a href="https://www.livrosabertos.abcd.usp.br/portaldelivrosUSP/catalog/book/1281">Livro da UrbVerde</a>.</p>',
    'Área de praças por habitante': '<p>A <strong>Área de praças por habitante</strong> representa a quantidade de área de praças e parques disponível para cada habitante do município. Esse indicador é fundamental para avaliar a qualidade ambiental e o acesso a espaços verdes dentro do planejamento urbano.</p><p><strong>Resolução:</strong> Não se aplica.</p><p><strong>Metodologia:</strong> O cálculo segue a equação: IAV = Soma da área total dos polígonos <em>OpenStreetMap (OSM)</em> / Número total de habitantes IBGE. Técnicas de geoprocessamento foram aplicadas para somar os polígonos do OSM e cruzá-los com os dados populacionais do Censo IBGE (2022), permitindo a análise em escala municipal e intraurbana.</p><p><strong>Cuidados ao analisar os dados:</strong> Os polígonos de praças e parques são provenientes do <em>OpenStreetMap</em> e seguem a licença ODbl (Open Data License). A validação desses dados colaborativos ocorre periodicamente, conforme a disponibilidade de dados oficiais e novas atualizações da plataforma.</p><p><strong>Fontes:</strong> UN-Habitat (2018). <a href="https://unhabitat.org/sdg-indicator-1171-training-module-public-space">SDG Indicator 11.7.1 Training Module: Public Space</a>. United Nations Human Settlement. NUCCI, J. C. (2008). Qualidade ambiental e adensamento urbano: um estudo de ecologia e planejamento da paisagem aplicado ao distrito de Santa Cecília (MSP). Autor, Curitiba.</p>',
    'Área atendida pelas praças': '<p>A <strong>Área atendida pelas Praças</strong> representa a porcentagem da área do município que está dentro de um raio de 400 metros de uma praça ou parque. Essa informação é útil para entender a acessibilidade aos espaços verdes urbanos e apoiar o planejamento urbano sustentável.</p><p><strong>Resolução:</strong> Não se aplica.</p><p><strong>Metodologia:</strong> A análise é feita por meio da intersecção entre buffers de 400 metros ao redor dos polígonos do OpenStreetMap (OSM) e os setores censitários. A partir dessa intersecção, calcula-se a proporção da área de cada setor censitário que está coberta pelos buffers, permitindo estimar a cobertura de espaços verdes urbanos acessíveis à população.</p><p><strong>Cuidados ao analisar os dados:</strong> Os buffers estão sendo reformulados conforme a nova categorização dos espaços livres mapeados. Os raios dos buffers podem variar de acordo com o tamanho e a categoria de cada espaço verde.</p><p><strong>Fonte:</strong> FANTIN, M.; PEDRASSOLI, J. C.; MELO, B. M. de; MENEZES, G. P.; MARTINES, M. R. "Inteligência geográfica na construção de políticas públicas: rumo à plataforma de monitoramento de áreas verdes urbanas do Estado de São Paulo". Interações, v. 23, p. 907-922, 2022.</p>',
    'População atendida pelas praças (%)':'<p>A <strong>População atendida pelas praças (em %)</strong> representa a porcentagem da quantidade de pessoas que vivem em setores censitários atendidos por pelo menos uma praça ou parque em um raio de até 400 metros. Esse dado é fundamental para avaliar o acesso da população a áreas verdes e o impacto desses espaços na qualidade de vida urbana.</p> <p><strong>Resolução:</strong> Não se aplica.</p> <p><strong>Metodologia:</strong> A estimativa é feita identificando a interseção entre os setores censitários urbanos e os buffers gerados a partir dos polígonos de praças e parques. Dessa forma, é possível calcular a quantidade de habitantes de cada setor censitário que tem acesso a pelo menos uma praça ou parque.</p> <p><strong>Cuidados ao analisar os dados:</strong> O número de habitantes atendidos pode variar não apenas pela presença de praças e parques, mas também pela densidade populacional de cada setor censitário. Os buffers estão sendo reformulados conforme uma nova categorização dos espaços livres mapeados. Assim, os raios dos buffers podem sofrer alterações dependendo do tamanho de cada categoria.</p> <p><strong>Fontes:</strong> FANTIN, M. et al. "Inteligência geográfica na construção de políticas públicas: rumo à plataforma de monitoramento de áreas verdes urbanas do Estado de São Paulo". Interações, v. 23, pp. 907-922, 2022. GOMES, J. G. et al. "Medindo a desigualdade no acesso às praças e parques urbanos com o suporte de indicadores da plataforma UrbVerde". Anais do XX Simpósio Brasileiro de Sensoriamento Remoto, v. 20, pp. 1474-1477, 2023.</p>',
    'Cobertura vegetal em parques e praças': '<p>A <strong>Cobertura Vegetal em Parques e Praças</strong> indica o percentual da área da malha urbana do município que está coberta por vegetação dentro dos limites das praças e parques mapeados. Esse dado é útil para avaliar a função ecológica e o conforto ambiental desses espaços públicos.</p> <p><strong>Resolução:</strong> Não se aplica (dado vetorial por município).</p> <p><strong>Metodologia:</strong> Com base nos polígonos de praças e parques obtidos do <em>OpenStreetMap</em> (OSM), foi aplicado o Modelo Linear de Mistura Espectral (MLME) às imagens do <em>Landsat-8</em> para estimar a vegetação. Calcula-se, então, o percentual de vegetação presente dentro da área total dos espaços públicos em relação à malha urbana do município: (área vegetada em praças e parques / área urbana total) × 100.</p> <p><strong>Cuidados ao analisar os dados:</strong> Os limites dos parques e praças podem variar conforme a atualização do OSM. O modelo pode confundir sombra com vegetação em áreas densamente arborizadas.</p> <p><strong>Fonte:</strong> OpenStreetMap (OSM), Landsat-8, processamento UrbVerde.</p>',
    'Impermeabilização do solo em parques e praças': '<p>A <strong>Impermeabilização do Solo em Parques e Praças</strong> indica o percentual da área desses espaços públicos que está coberta por superfícies impermeáveis. Esse dado auxilia no planejamento de infraestrutura verde e drenagem urbana.</p> <p><strong>Resolução:</strong> Não se aplica (dado vetorial por município).</p> <p><strong>Metodologia:</strong> Com base nos polígonos das praças e parques do <em>OpenStreetMap</em>, foi utilizada a classificação obtida pelo algoritmo <em>Random Forest</em> e MLME a partir das imagens do <em>Landsat-8</em>. O cálculo considera a área impermeável sobre os espaços públicos, expressa como: (área impermeável em praças e parques / área urbana total) × 100.</p> <p><strong>Cuidados ao analisar os dados:</strong> Áreas pavimentadas dentro de praças (calçadas, quadras) influenciam o índice. A precisão depende da resolução da imagem e da qualidade do mapeamento vetorial.</p> <p><strong>Fonte:</strong> OpenStreetMap (OSM), Landsat-8, processamento UrbVerde.</p>',

    // Socioeconômicos:
    'Quantidade de habitantes': '<p>A <strong>Quantidade de Habitantes</strong> mostra o total de pessoas que vivem nos setores censitários urbanos de cada município. Esse dado é fundamental para planejar políticas públicas, avaliar o acesso a serviços essenciais e entender a distribuição da população nas cidades.</p> <p><strong>Fonte:</strong> Instituto Brasileiro de Geografia e Estatística (IBGE), <a href="https://www.ibge.gov.br/estatisticas/sociais/trabalho/22827-censo-demografico-2022.html">Censo Demográfico 2022</a>.</p>',
    'Densidade demográfica': '<p>A <strong>Densidade Demográfica</strong> representa o número de habitantes por quilômetro quadrado em cada setor censitário urbano. Esse indicador ajuda a identificar áreas com maior adensamento populacional e orientar políticas de infraestrutura, mobilidade e áreas verdes.</p> <p><strong>Fonte:</strong> IBGE, <a href="https://www.ibge.gov.br/estatisticas/sociais/trabalho/22827-censo-demografico-2022.html">Censo Demográfico 2022</a>.</p>',
    'Percentual de alfabetizados': '<p>O <strong>Percentual de Alfabetizados</strong> indica a proporção da população urbana com capacidade de ler e escrever. Esse dado é importante para avaliar o acesso à educação e planejar políticas públicas voltadas à inclusão educacional.</p> <p><strong>Fonte:</strong> IBGE, <a href="https://www.ibge.gov.br/estatisticas/sociais/trabalho/22827-censo-demografico-2022.html">Censo Demográfico 2022</a>.</p>',
    'Renda média do responsável da casa': '<p>A <strong>Renda Média do Responsável pela Casa</strong> reflete o rendimento médio mensal da pessoa responsável pelo domicílio. Esse dado é essencial para mapear desigualdades socioeconômicas e orientar políticas de redistribuição de renda e justiça social.</p> <p><strong>Fonte:</strong> IBGE, <a href="https://www.ibge.gov.br/estatisticas/sociais/trabalho/22827-censo-demografico-2022.html">Censo Demográfico 2022</a>.</p>',
    'Percentual de crianças': '<p>O <strong>Percentual de Crianças</strong> representa a proporção da população urbana com até 9 anos de idade. Esse indicador é relevante para políticas voltadas à infância, como a oferta de creches, escolas e áreas de lazer.</p> <p><strong>Fonte:</strong> IBGE, <a href="https://www.ibge.gov.br/estatisticas/sociais/trabalho/22827-censo-demografico-2022.html">Censo Demográfico 2022</a>.</p>',
    'Percentual de idosos': '<p>O <strong>Percentual de Idosos</strong> indica a proporção da população urbana com 60 anos ou mais. Esse dado é essencial para o planejamento de políticas de saúde, acessibilidade e mobilidade voltadas à população idosa.</p> <p><strong>Fonte:</strong> IBGE, <a href="https://www.ibge.gov.br/estatisticas/sociais/trabalho/22827-censo-demografico-2022.html">Censo Demográfico 2022</a>.</p>',
    'Percentual de mulheres': '<p>O <strong>Percentual de Mulheres</strong> mostra a proporção de pessoas do sexo feminino nos setores urbanos. Esse dado contribui para a formulação de políticas de equidade de gênero e proteção social.</p> <p><strong>Fonte:</strong> IBGE, <a href="https://www.ibge.gov.br/estatisticas/sociais/trabalho/22827-censo-demografico-2022.html">Censo Demográfico 2022</a>.</p>',
    'Percentual de homens': '<p>O <strong>Percentual de Homens</strong> indica a proporção de pessoas do sexo masculino nos setores urbanos. Esse dado pode ser usado em conjunto com outros indicadores para análises demográficas e sociais.</p> <p><strong>Fonte:</strong> IBGE, <a href="https://www.ibge.gov.br/estatisticas/sociais/trabalho/22827-censo-demografico-2022.html">Censo Demográfico 2022</a>.</p>',
    'Percentual de pessoas brancas': '<p>O <strong>Percentual de Pessoas Brancas</strong> indica a proporção da população urbana que se identifica como branca, conforme declarado no Censo 2022. Esses dados são fundamentais para o mapeamento das desigualdades raciais e formulação de políticas de equidade.</p> <p><strong>Fonte:</strong> IBGE, <a href="https://www.ibge.gov.br/estatisticas/sociais/trabalho/22827-censo-demografico-2022.html">Censo Demográfico 2022</a>.</p>',
    'Percentual de pessoas pretas': '<p>O <strong>Percentual de Pessoas Pretas</strong> indica a proporção da população urbana que se identifica como preta, conforme declarado no Censo 2022. Esses dados são fundamentais para o mapeamento das desigualdades raciais e formulação de políticas de equidade.</p> <p><strong>Fonte:</strong> IBGE, <a href="https://www.ibge.gov.br/estatisticas/sociais/trabalho/22827-censo-demografico-2022.html">Censo Demográfico 2022</a>.</p>',
    'Percentual de pessoas pardas': '<p>O <strong>Percentual de Pessoas Pardas</strong> indica a proporção da população urbana que se identifica como parda, conforme declarado no Censo 2022. Esses dados são fundamentais para o mapeamento das desigualdades raciais e formulação de políticas de equidade.</p> <p><strong>Fonte:</strong> IBGE, <a href="https://www.ibge.gov.br/estatisticas/sociais/trabalho/22827-censo-demografico-2022.html">Censo Demográfico 2022</a>.</p>',
    'Percentual de pessoas amarelas': '<p>O <strong>Percentual de Pessoas Amarelas</strong> indica a proporção da população urbana que se identifica como amarela, conforme declarado no Censo 2022. Esses dados são fundamentais para o mapeamento das desigualdades raciais e formulação de políticas de equidade.</p> <p><strong>Fonte:</strong> IBGE, <a href="https://www.ibge.gov.br/estatisticas/sociais/trabalho/22827-censo-demografico-2022.html">Censo Demográfico 2022</a>.</p>',
    'Percentual de pessoas indigenas': '<p>O <strong>Percentual de Pessoas Indígenas</strong> indica a proporção da população urbana que se identifica como indígena, conforme declarado no Censo 2022. Esses dados são fundamentais para o mapeamento das desigualdades raciais e formulação de políticas de equidade.</p> <p><strong>Fonte:</strong> IBGE, <a href="https://www.ibge.gov.br/estatisticas/sociais/trabalho/22827-censo-demografico-2022.html">Censo Demográfico 2022</a>.</p>',

    // Hidrologia:
    'Massas da água': '<p>O <strong>Mapa de Massas da água</strong> representa os corpos hídricos do estado, como lagos, represas e reservatórios, classificados por tipologia e domínio das águas (estaduais ou federais).</p> <p><strong>Resolução:</strong> 30 metros (raster).</p> <p><strong>Metodologia:</strong> Os dados foram obtidos da Agência Nacional de Águas (ANA) e organizados em imagens raster. As massas d’água são classificadas com base em tipologia (naturais ou artificiais) e destacadas visualmente em azul.</p> <p><strong>Cuidados ao analisar os dados:</strong> A resolução pode limitar a visualização de corpos hídricos muito pequenos. A delimitação pode variar conforme a época do ano e o nível da água.</p> <p><strong>Fonte:</strong> Agência Nacional de Águas (ANA), 2020.</p>',
    'Rios': '<p>A camada de <strong>Rios</strong> representa a rede de drenagem superficial do Estado de São Paulo, incluindo os principais cursos d’água naturais.</p> <p><strong>Resolução:</strong> Escala 1:50.000 (shapefile vetorial).</p> <p><strong>Metodologia:</strong> As linhas foram geradas com base no Modelo Digital de Elevação (MDE), a partir de curvas de nível das cartas topográficas do IBGE, IGG e Exército Brasileiro.</p> <p><strong>Cuidados ao analisar os dados:</strong> Os cursos d’água são representações vetoriais baseadas em modelos de terreno. Pequenos córregos ou canais urbanos podem não estar mapeados.</p> <p><strong>Fonte:</strong> SEMIL (Cessão de Dados Espaciais), IBGE, IGG, DSG (2008).</p>',
    'Perigo de inundação em Diadema (classes)': '<p>O <strong>Mapa de Perigo de Inundação em Diadema</strong> classifica as áreas do município em seis faixas de risco, com cores variando do verde (risco nulo) ao vermelho (risco muito alto), com base em variáveis físicas e urbanas.</p> <p><strong>Resolução:</strong> 30 metros (raster).</p> <p><strong>Metodologia:</strong> O índice foi calculado a partir de cinco critérios: valores de HAND (Height Above Nearest Drainage), elevação, declividade, proximidade de corpos hídricos e o índice NDBI (Normalized Difference Built-up Index). </p> <p><strong>Cuidados ao analisar os dados:</strong> O mapa mostra perigo potencial. A escala local permite alta precisão, mas está sujeita a limitações de cobertura urbana e dinâmica hidrológica.</p> <p><strong>Fonte:</strong> UrbVerde, 2025.</p>',
    'Impermeabilização do solo nas APPs': '<p>A camada de <strong>Impermeabilização do solo nas APPs</strong> indica o percentual de áreas impermeabilizadas dentro das Áreas de Preservação Permanente (APPs) associadas a rios e nascentes no município de Diadema.</p><p><strong>Resolução:</strong> Escala municipal (shapefile vetorial).</p><p><strong>Metodologia:</strong> As APPs foram delimitadas manualmente, aplicando-se um buffer de 30 metros ao longo das linhas de drenagem e de 50 metros ao redor de cada ponto de nascente, a partir do shapefile de drenagem do GeoDiadema. Posteriormente, cruzaram-se essas delimitações com os dados de <em>Percentual de Cobertura Vegetal (PCV – ano de 2024)</em>, produzidos pela Plataforma UrbVerde. O resultado representa a proporção de áreas impermeabilizadas em APPs no município.</p><p><strong>Cuidados ao analisar os dados:</strong> Os valores estão sujeitos à qualidade do shapefile de drenagem do GeoDiadema e à atualização do mapeamento de cobertura vegetal (PCV). Por enquanto, a análise está restrita ao município de Diadema.</p><p><strong>Fonte:</strong> UrbVerde (2024); GeoDiadema.</p>',
    'Cobertura vegetal nas APPs': '<p>A camada de <strong>Cobertura vegetal nas APPs</strong> representa a proporção de áreas vegetadas existentes dentro das Áreas de Preservação Permanente (APPs) associadas a rios e nascentes no município de Diadema.</p><p><strong>Resolução:</strong> Escala municipal (shapefile vetorial).</p><p><strong>Metodologia:</strong> As APPs foram delimitadas manualmente, aplicando-se um buffer de 30 metros ao longo das linhas de drenagem e de 50 metros ao redor de cada nascente, com base no shapefile de drenagem do GeoDiadema. Posteriormente, essas áreas foram cruzadas com os dados de <em>Percentual de Solo Impermeabilizado (PSI – ano de 2024)</em>, produzidos pela Plataforma UrbVerde. O indicador final mostra a cobertura vegetal remanescente nas APPs.</p><p><strong>Cuidados ao analisar os dados:</strong> A acurácia depende da qualidade do shapefile de drenagem do GeoDiadema e da atualização da base de mapeamento UrbVerde (PSI). Por enquanto, a análise está restrita ao município de Diadema.</p><p><strong>Fonte:</strong> UrbVerde (2024); GeoDiadema.</p>',

    // Agricultura urbana e segurança alimentar:
    'Distância média até pontos de agricultura urbana': '<p>A <strong>Distância média até pontos de agricultura urbana</strong> indica a média de metros que os moradores precisam percorrer para alcançar o ponto de agricultura urbana mais próximo a partir do seu setor censitário.</p><p><strong>Resolução:</strong> Não se aplica.</p><p><strong>Metodologia:</strong> Foi calculada a distância geométrica entre o centróide de cada setor censitário urbano e o ponto de agricultura urbana mais próximo, em metros.</p><p><strong>Cuidados ao analisar os dados:</strong> A métrica considera distância em linha reta (geodésica) e não o caminho real por ruas ou calçadas. A localização dos pontos depende da base de dados atualizada sobre iniciativas de agricultura urbana.</p>',
    'Distância média até restaurantes populares': '<p>A <strong>Distância média até restaurantes populares</strong> representa a média de metros entre o centróide de cada setor censitário urbano e o restaurante popular mais próximo.</p><p><strong>Resolução:</strong> Não se aplica.</p><p><strong>Metodologia:</strong> Utilizando os centróides dos setores censitários, foi calculada a distância geométrica em metros até o restaurante popular mais próximo.</p><p><strong>Cuidados ao analisar os dados:</strong> A análise considera a distância em linha reta. A presença ou ausência de restaurantes populares em regiões específicas pode impactar diretamente a acessibilidade alimentar da população vulnerável.</p>',
    'Distância média até feiras livres': '<p>A <strong>Distância média até feiras livres</strong> mostra o quanto os moradores de cada setor censitário urbano estão distantes, em média, da feira livre mais próxima.</p><p><strong>Resolução:</strong> Não se aplica.</p><p><strong>Metodologia:</strong> A partir dos centróides dos setores censitários, foi medida a distância em metros até a feira livre mais próxima.</p><p><strong>Cuidados ao analisar os dados:</strong> A métrica é baseada em distância geométrica, e não reflete necessariamente o trajeto percorrido a pé. A qualidade da base de dados de feiras pode afetar os resultados.</p>',
    'Desertos alimentares': '<p>O <strong>Índice de desertos alimentares</strong> indica a quantidade de estabelecimentos que vendem alimentos in natura acessíveis em até 15 minutos de caminhada, a cada mil habitantes de cada setor censitário urbano.</p><p><strong>Resolução:</strong> Não se aplica.</p><p><strong>Metodologia:</strong> A partir dos centróides dos setores censitários, foram desenhados polígonos de caminhada de 15 minutos no programa <em>Vanhalla</em> do QGIS. Dentro de cada polígono, foram contados os estabelecimentos de venda de alimentos in natura acessíveis a pé. Esse valor foi então dividido pela população (em milhares) de cada setor censitário.</p><p><strong>Cuidados ao analisar os dados:</strong> Setores com valores baixos indicam maior risco de deserto alimentar. A análise depende da precisão da base de estabelecimentos e da malha viária usada para cálculo da caminhada.</p>',
    'Pântanos alimentares': '<p>O <strong>Índice de pântanos alimentares</strong> representa a quantidade de estabelecimentos que vendem alimentos ultraprocessados acessíveis em até 15 minutos de caminhada, a cada mil habitantes de cada setor censitário urbano.</p><p><strong>Resolução:</strong> Não se aplica.</p><p><strong>Metodologia:</strong> Utilizando o programa <em>Vanhalla</em> no QGIS, foram desenhados polígonos de caminhada de 15 minutos ao redor dos centróides dos setores censitários. Dentro desses polígonos, foi contada a quantidade de estabelecimentos que comercializam alimentos ultraprocessados. O valor foi dividido pela população (em milhares) de cada setor.</p><p><strong>Cuidados ao analisar os dados:</strong> Setores com valores altos indicam maior exposição a alimentos não saudáveis. A precisão depende do cadastro atualizado dos estabelecimentos comerciais.</p>',
    'Densidade de estabelecimentos comerciais de produtos in natura': '<p>A <strong>Densidade de estabelecimentos de produtos in natura</strong> indica a concentração de comércios com alta probabilidade de venda de alimentos saudáveis dentro de cada setor censitário urbano.</p><p><strong>Resolução:</strong> Não se aplica.</p><p><strong>Metodologia:</strong> A partir da base da Receita Federal com CNPJs ativos no município de Diadema, foram filtrados os estabelecimentos relacionados à venda de alimentos. Em seguida, classificaram-se os que vendem produtos in natura. A contagem por setor censitário resultou no indicador de densidade.</p><p><strong>Cuidados ao analisar os dados:</strong> A classificação baseia-se em códigos de atividade econômica e pode conter imprecisões. A densidade não reflete diretamente a qualidade ou acessibilidade dos produtos vendidos.</p>',
    'Densidade de estabelecimentos comerciais de produtos ultraprocessados': '<p>A <strong>Densidade de estabelecimentos de produtos ultraprocessados</strong> indica a quantidade de comércios que provavelmente vendem alimentos não saudáveis em cada setor censitário urbano.</p><p><strong>Resolução:</strong> Não se aplica.</p><p><strong>Metodologia:</strong> Com base na mesma lista de CNPJs ativos da Receita Federal em Diadema, foram identificados os estabelecimentos relacionados à venda de alimentos e classificados os que comercializam produtos ultraprocessados. A contagem por setor censitário gerou o valor de densidade.</p><p><strong>Cuidados ao analisar os dados:</strong> A categorização dos produtos depende da correta atribuição dos códigos de atividade econômica e da atualização do banco de dados comercial.</p>',
    'Áreas prioritárias para implantação de agricultura urbana (nivel 1)': '<p>As <strong>Áreas prioritárias para agricultura urbana – Nível 1</strong> são setores censitários identificados como prioritários para a implantação de agricultura urbana em lajes e topos de edifícios, com base em critérios sociais, populacionais e de vulnerabilidade urbana.</p><p><strong>Resolução:</strong> Não se aplica.</p><p><strong>Metodologia:</strong> Foram selecionados os setores com densidade demográfica acima de 12.795 hab/km² e renda média domiciliar abaixo de R$ 2.322,00. A seguir, cruzaram-se esses setores com os localizados em favelas e comunidades urbanas, segundo o IBGE.</p><p><strong>Cuidados ao analisar os dados:</strong> Os critérios usados priorizam regiões com alta demanda social e carência de acesso a alimentos frescos. A renda média e os limites de favelas se baseiam em dados do Censo mais recente.</p>',
    'Áreas prioritárias para implantação de agricultura urbana (nível 2)': '<p>As <strong>Áreas prioritárias para agricultura urbana – Nível 2</strong> são setores censitários com alto potencial para a instalação de agricultura urbana em espaços verticais, considerando aspectos sociais e demográficos.</p><p><strong>Resolução:</strong> Não se aplica.</p><p><strong>Metodologia:</strong> Foram selecionados os setores com densidade demográfica superior a 12.795 hab/km² e renda média do responsável pelo domicílio inferior a R$ 2.322,00. A seleção não inclui obrigatoriamente setores classificados como favelas ou comunidades urbanas.</p><p><strong>Cuidados ao analisar os dados:</strong> A seleção se baseia em critérios estruturais e socioeconômicos. A ausência do critério de favela neste nível amplia a abrangência das áreas consideradas, mas pode incluir setores com maior infraestrutura urbana.</p>',

    // Riscos climáticos
    'Riscos à ondas de calor': '<p>O <strong>Indicador de Risco Climático a Ondas de Calor</strong> (rCALOR) representa o risco espacial final de um setor censitário urbano ser impactado por ondas de calor, variando de 0,00 (menor risco) a 1,00 (maior risco). Ele integra três dimensões principais: ameaça, exposição e vulnerabilidade.</p><p><strong>Resolução:</strong> Não se aplica.</p><p><strong>Metodologia:</strong> O índice é calculado pela média geométrica entre as três dimensões:</p><p><code>rCALOR = ∛(ameacaCALOR * expoCALOR * vulnerabCALOR)</code></p><p><strong>Ameaça (ameacaCALOR):</strong> composta exclusivamente pela normalização da temperatura máxima de superfície (iTEMP_MAX).</p><p><strong>Exposição (expoCALOR):</strong> baseada exclusivamente na densidade demográfica (iDENSIDADE).</p><p><strong>Vulnerabilidade (vulnerabCALOR):</strong> calculada pela média entre a sensibilidade e o inverso da capacidade adaptativa:</p><p><code>v = [sensibCALOR + (1 - cadaptCALOR)] / 2</code></p><ul><li><strong>Sensibilidade (sensibCALOR):</strong> baseada na normalização da população em faixa etária sensível (iPOP_SENS).</li><li><strong>Capacidade adaptativa (cadaptCALOR):</strong> média aritmética das variáveis normalizadas de renda, acesso à água encanada, acesso à saúde e cobertura vegetal: <code>(iRENDA + iAGUA + iSAUDE + iPCV) / 4</code></li></ul><p><strong>Cuidados ao analisar os dados:</strong> Este índice é comparativo dentro do município, e os resultados variam conforme a qualidade e atualização das variáveis envolvidas. Setores com valores mais próximos de 1 indicam áreas mais críticas que podem demandar ações urgentes de adaptação climática.</p>',
    'Riscos à arboviroses': '<p>O <strong>Indicador de Risco Climático a Arboviroses</strong> (rARBOVIROSE) estima a probabilidade de ocorrência de arboviroses, como dengue, em áreas urbanas, combinando variáveis de clima, infraestrutura e população vulnerável. O índice varia de 0,00 (menor risco) a 1,00 (maior risco).</p><p><strong>Resolução:</strong> Não se aplica.</p><p><strong>Metodologia:</strong> O índice é calculado pela média geométrica das três dimensões do risco:</p><p><code>rARBOVIROSE = ∛(ameacaARBOVIROSE * expoARBOVIROSE * vulnerabARBOVIROSE)</code></p><p><strong>Ameaça (ameacaARBOVIROSE):</strong> média aritmética das variáveis normalizadas: temperatura média, índice de casos de dengue e índice pluviométrico.</p><p><strong>Exposição (expoARBOVIROSE):</strong> composta exclusivamente pela normalização da densidade demográfica (iDENSIDADE).</p><p><strong>Vulnerabilidade (vulnerabARBOVIROSE):</strong> calculada como:</p><p><code>v = [sensibARBOVIROSE + (1 - cadaptARBOVIROSE)] / 2</code></p><ul><li><strong>Sensibilidade:</strong> média das variáveis normalizadas: população sensível, domicílios sem água, domicílios sem esgoto e domicílios sem coleta de lixo.</li><li><strong>Capacidade adaptativa:</strong> média das variáveis normalizadas: renda, distância a equipamentos de saúde e alfabetização do responsável pelo domicílio.</li></ul><p><strong>Cuidados ao analisar os dados:</strong> As áreas com maior risco são aquelas onde há simultaneamente alta temperatura, maior densidade, baixa infraestrutura e população mais vulnerável. O índice orienta estratégias de prevenção e resposta a surtos de doenças transmitidas por vetores.</p>',
    'Vulnerabilidade alimentar e nutricional': '<p>O <strong>Indicador de Vulnerabilidade Alimentar e Nutricional</strong> (vulnerabSAN) mede o grau de vulnerabilidade dos setores censitários urbanos quanto ao acesso, segurança e qualidade alimentar da população. Varia entre 0,00 (menor vulnerabilidade) e 1,00 (maior vulnerabilidade).</p><p><strong>Resolução:</strong> Não se aplica.</p><p><strong>Metodologia:</strong> O indicador é construído a partir da média entre a sensibilidade e o inverso da capacidade adaptativa:</p><p><code>v = [sensibSAN + (1 - cadaptSAN)] / 2</code></p><ul><li><strong>Sensibilidade (sensibSAN):</strong> média aritmética das variáveis normalizadas: população até 9 anos, densidade domiciliar, domicílios sem água, beneficiários do PBF, pessoas que não realizam 3 refeições por dia e pessoas que consomem ultraprocessados.</li><li><strong>Capacidade adaptativa (cadaptSAN):</strong> média ponderada das variáveis normalizadas: <code>0,5 × iRENDA + 0,25 × iREST_POP + 0,25 × iENERGIA</code>, que representam renda, distância até restaurante popular e interrupções de energia elétrica, respectivamente.</li></ul><p><strong>Cuidados ao analisar os dados:</strong> Valores mais altos indicam territórios com maior fragilidade alimentar, sendo prioritários para políticas de segurança alimentar e combate à fome.</p>',
    'Riscos à inundações': '<p>O <strong>Indicador de Risco Climático a Inundações</strong> (rINUNDA) estima o risco de impacto por inundações em áreas urbanas, variando de 0,00 (menor risco) a 1,00 (maior risco), e considera as dimensões de ameaça, exposição e vulnerabilidade.</p><p><strong>Resolução:</strong> Não se aplica.</p><p><strong>Metodologia:</strong> O índice é calculado pela média geométrica das três dimensões:</p><p><code>rINUNDA = ∛(ameacaINUNDA * expoINUNDA * vulnerabINUNDA)</code></p><ul><li><strong>Ameaça (ameacaINUNDA):</strong> valor ponderado entre duas variáveis normalizadas: perigo de inundação e densidade de ocorrências registradas de inundações.</li><li><strong>Exposição (expoINUNDA):</strong> valor ponderado entre: densidade demográfica e densidade hierárquica do sistema viário.</li><li><strong>Vulnerabilidade (vulnerabINUNDA):</strong> média entre sensibilidade e o inverso da capacidade adaptativa:</li></ul><p><code>v = [sensibINUNDA + (1 - cadaptINUNDA)] / 2</code><ul><li><strong>Sensibilidade:</strong> média das variáveis: baixa densidade de bocas de lobo, ausência de calçada e ausência de coleta de lixo.</li><li><strong>Capacidade adaptativa:</strong> média ponderada das variáveis: renda, permeabilidade do solo e pessoas responsáveis alfabetizadas.</li></ul><p><strong>Cuidados ao analisar os dados:</strong> O índice reflete tanto fatores estruturais (drenagem, pavimentação) quanto sociais, sendo essencial para planejamento de infraestrutura e resposta a desastres urbanos.</p>',
    'Desenvolvimento social do habitat para favelas': '<p>O <strong>Índice de Desenvolvimento Social do Habitat (IDESH)</strong> mede o grau de vulnerabilidade dos setores censitários localizados em favelas e comunidades urbanas, considerando fatores habitacionais, urbanos, sociais e de risco. O índice varia de 0,00 (melhor situação) a 1,00 (pior situação).</p><p><strong>Resolução:</strong> Não se aplica.</p><p><strong>Metodologia:</strong> O IDESH é calculado como:</p><p><code>iDESH = (∛(iHABITAT × iURBANA × iSOCIAL)) × 0,75 + (iRISCO × 0,25)</code></p><ul><li><strong>iHABITAT:</strong> média das variáveis: densidade domiciliar, domicílios sem água, sem esgoto e sem banheiro exclusivo.</li><li><strong>iURBANA:</strong> média das variáveis: domicílios que despejam esgoto de forma inadequada, sem coleta de lixo, sem bueiro, sem pavimentação e sem calçada.</li><li><strong>iSOCIAL:</strong> média das variáveis: renda da pessoa responsável, pessoas no PBF, jovens de 15 a 19 anos não alfabetizados, responsáveis jovens (até 24 anos) e responsáveis não alfabetizados.</li><li><strong>iRISCO:</strong> valor ponderado segundo a gravidade da sobreposição a áreas de risco geotécnico ou hidrológico, com pesos para os níveis R1 a R4.</li></ul><p><strong>Cuidados ao analisar os dados:</strong> Este indicador combina vulnerabilidades estruturais, sociais e ambientais, sendo um importante instrumento para priorização de investimentos públicos em territórios periféricos e comunidades urbanas.</p>',

    // Emissões
    'Emissões do município (tCO₂e)': '<p>As <strong>Emissões do município (tCO₂e)</strong> representam o somatório das emissões líquidas originadas de fontes antrópicas, agregadas por setor de emissão e deduzidas da remoção por sumidouros.</p><p><strong>Resolução:</strong> Não se aplica.</p><p><strong>Unidade de medida:</strong> toneladas de CO₂ equivalente (tCO₂e), determinadas pelo fator GWP-100.</p><p><strong>Metodologia:</strong> Os dados de emissões de Gases de Efeito Estufa (GEE) são coletados na plataforma SEEG em planilhas CSV, aplicando o filtro de “emissões totais” para cada município (séries até 2023). As planilhas são importadas no Google Earth Engine para ordenar os dados e gerar uma planilha agregada (2016–2023), que é então levada ao QGIS para processamento em ambiente SIG. Nesse procedimento, realiza-se a sintetização das variáveis e o mapeamento dos resultados utilizando a base vetorial de municípios do IBGE (Censo 2022) como unidade escalar.</p><p><strong>Cuidados ao analisar os dados:</strong> Os valores representam emissões líquidas e dependem das classificações setoriais e das atualizações do SEEG. A série cobre 2016–2023 e está condicionada à disponibilidade e consistência das bases municipais.</p><p><strong>Fontes:</strong><br>IBGE. Censo Demográfico 2022: população e domicílios: primeiros resultados. 2023. Disponível em: <a href="https://www.ibge.gov.br/estatisticas/sociais/trabalho/22827-censodemografico-2022.html" target="_blank">https://www.ibge.gov.br/estatisticas/sociais/trabalho/22827-censodemografico-2022.html</a>.<br>MCTI. Ministério da Ciência, Tecnologia e Inovação. Relatório do Inventário Nacional das Emissões Antrópicas por Fontes e das Remoções por Sumidouros de Gases de Efeito Estufa do Brasil. Brasília, 2024. Disponível em: <a href="https://www.gov.br/mcti/pt-br/acompanhe-o-mcti/sirene/publicacoes/relatorios-bienais-de-transparencia-btrs/Relatorio_deInventario_NacionalNIR_2024_PORT.pdf" target="_blank">https://www.gov.br/mcti/pt-br/acompanhe-o-mcti/sirene/publicacoes/relatorios-bienais-de-transparencia-btrs/Relatorio_deInventario_NacionalNIR_2024_PORT.pdf</a><br>MMA – Ministério do Meio Ambiente. PNIA – PAINEL NACIONAL DE INDICADORES AMBIENTAIS. Indicadores Nacionais. Portal.<br>SEEG. Análise das emissões de gases de efeito estufa e suas implicações para as metas climáticas do Brasil. 2024. Disponível em: <a href="https://energiaeambiente.org.br/como-usar-o-seeg-municipios-sistema-de-estimativas-de-emissoes-e-remocoes-de-gases-de-efeito-estufa-20221011" target="_blank">https://energiaeambiente.org.br/como-usar-o-seeg-municipios-sistema-de-estimativas-de-emissoes-e-remocoes-de-gases-de-efeito-estufa-20221011</a>.</p>',
    'Emissões do município por habitante (tCO₂e/hab)': '<p>O <strong>Índice de Emissões por Habitante (tCO₂e/hab)</strong> expressa as emissões totais de GEE do município referidas à população residente, resultando de síntese produzida a partir do cruzamento com dados populacionais.</p><p><strong>Resolução:</strong> Não se aplica.</p><p><strong>Unidade de medida:</strong> toneladas de CO₂ equivalente por habitante (tCO₂e/hab), determinadas pelo fator GWP-100.</p><p><strong>Metodologia:</strong> As emissões são obtidas do SEEG (CSV) para cada município, importadas no Google Earth Engine e agregadas (2016–2023). No QGIS, realiza-se a sintetização das variáveis, incluindo o <em>índice de emissões por habitante (IEH)</em>, por meio da inclusão e cruzamento com dados populacionais e socioeconômicos. O mapeamento utiliza a base vetorial de municípios do IBGE (Censo 2022) como unidade escalar.</p><p><strong>Cuidados ao analisar os dados:</strong> O indicador depende da consistência das estimativas de emissões do SEEG e da população do Censo 2022; variações metodológicas e atualizações podem afetar comparações ao longo do período 2016–2023.</p><p><strong>Fontes:</strong><br>IBGE. Censo Demográfico 2022: população e domicílios: primeiros resultados. 2023. Disponível em: <a href="https://www.ibge.gov.br/estatisticas/sociais/trabalho/22827-censodemografico-2022.html" target="_blank">https://www.ibge.gov.br/estatisticas/sociais/trabalho/22827-censodemografico-2022.html</a>.<br>MCTI. Ministério da Ciência, Tecnologia e Inovação. Relatório do Inventário Nacional das Emissões Antrópicas por Fontes e das Remoções por Sumidouros de Gases de Efeito Estufa do Brasil. Brasília, 2024. Disponível em: <a href="https://www.gov.br/mcti/pt-br/acompanhe-o-mcti/sirene/publicacoes/relatorios-bienais-de-transparencia-btrs/Relatorio_deInventario_NacionalNIR_2024_PORT.pdf" target="_blank">https://www.gov.br/mcti/pt-br/acompanhe-o-mcti/sirene/publicacoes/relatorios-bienais-de-transparencia-btrs/Relatorio_deInventario_NacionalNIR_2024_PORT.pdf</a><br>MMA – Ministério do Meio Ambiente. PNIA – PAINEL NACIONAL DE INDICADORES AMBIENTAIS. Indicadores Nacionais. Portal.<br>SEEG. Análise das emissões de gases de efeito estufa e suas implicações para as metas climáticas do Brasil. 2024. Disponível em: <a href="https://energiaeambiente.org.br/como-usar-o-seeg-municipios-sistema-de-estimativas-de-emissoes-e-remocoes-de-gases-de-efeito-estufa-20221011" target="_blank">https://energiaeambiente.org.br/como-usar-o-seeg-municipios-sistema-de-estimativas-de-emissoes-e-remocoes-de-gases-de-efeito-estufa-20221011</a>.</p>',
    'Emissões originadas da agropecuária (tCO₂e)': '<p>As <strong>Emissões originadas da agropecuária</strong> (tCO₂e) reúnem as emissões de fontes antrópicas do setor agropecuário conforme classificações setoriais.</p><p><strong>Resolução:</strong> Não se aplica.</p><p><strong>Unidade de medida:</strong> toneladas de CO₂ equivalente (tCO₂e), determinadas pelo fator GWP-100.</p><p><strong>Metodologia:</strong> No SEEG, aplica-se o filtro de “emissão por setor” para Agropecuária e exportam-se planilhas CSV por município (até 2023). Os dados são importados no Google Earth Engine para agregação (2016–2023) e, em seguida, processados no QGIS para sintetização e mapeamento sobre a base vetorial de municípios do IBGE (Censo 2022).</p><p><strong>Componentes do setor:</strong></p><ul><li>Fermentação entérica;</li><li>Manejo de dejetos;</li><li>Cultivo de arroz;</li><li>Solos manejados;</li><li>Queima de resíduos agrícolas;</li><li>Calagem e aplicação de ureia.</li></ul><p><strong>Cuidados ao analisar os dados:</strong> As categorias e limites setoriais seguem o SEEG/MCTI; a série temporal (2016–2023) está sujeita a revisões e atualizações das bases.</p><p><strong>Fontes:</strong><br>IBGE. Censo Demográfico 2022: população e domicílios: primeiros resultados. 2023. Disponível em: <a href="https://www.ibge.gov.br/estatisticas/sociais/trabalho/22827-censodemografico-2022.html" target="_blank">https://www.ibge.gov.br/estatisticas/sociais/trabalho/22827-censodemografico-2022.html</a>.<br>MCTI. Ministério da Ciência, Tecnologia e Inovação. Relatório do Inventário Nacional das Emissões Antrópicas por Fontes e das Remoções por Sumidouros de Gases de Efeito Estufa do Brasil. Brasília, 2024. Disponível em: <a href="https://www.gov.br/mcti/pt-br/acompanhe-o-mcti/sirene/publicacoes/relatorios-bienais-de-transparencia-btrs/Relatorio_deInventario_NacionalNIR_2024_PORT.pdf" target="_blank">https://www.gov.br/mcti/pt-br/acompanhe-o-mcti/sirene/publicacoes/relatorios-bienais-de-transparencia-btrs/Relatorio_deInventario_NacionalNIR_2024_PORT.pdf</a><br>MMA – Ministério do Meio Ambiente. PNIA – PAINEL NACIONAL DE INDICADORES AMBIENTAIS. Indicadores Nacionais. Portal.<br>SEEG. Análise das emissões de gases de efeito estufa e suas implicações para as metas climáticas do Brasil. 2024. Disponível em: <a href="https://energiaeambiente.org.br/como-usar-o-seeg-municipios-sistema-de-estimativas-de-emissoes-e-remocoes-de-gases-de-efeito-estufa-20221011" target="_blank">https://energiaeambiente.org.br/como-usar-o-seeg-municipios-sistema-de-estimativas-de-emissoes-e-remocoes-de-gases-de-efeito-estufa-20221011</a>.</p>',
    'Emissões originadas de energia (tCO₂e)': '<p>As <strong>Emissões originadas de energia</strong> (tCO₂e) abrangem as emissões associadas à produção, transformação, transporte e consumo de energia.</p><p><strong>Resolução:</strong> Não se aplica.</p><p><strong>Unidade de medida:</strong> toneladas de CO₂ equivalente (tCO₂e), determinadas pelo fator GWP-100.</p><p><strong>Metodologia:</strong> No SEEG, seleciona-se “emissão por setor” para Energia, exportando planilhas CSV municipais (até 2023). Os dados são integrados no Google Earth Engine (2016–2023) e processados no QGIS para sintetização e mapeamento com a base vetorial de municípios do IBGE (Censo 2022).</p><p><strong>Componentes do setor:</strong></p><ul><li>Produção de energia;</li><li>Transformação de energia;</li><li>Transporte de energia;</li><li>Consumo de energia.</li></ul><p><strong>Cuidados ao analisar os dados:</strong> A cobertura e a desagregação seguem as definições setoriais; as estimativas refletem dados consolidados até 2023 no SEEG.</p><p><strong>Fontes:</strong><br>IBGE. Censo Demográfico 2022: população e domicílios: primeiros resultados. 2023. Disponível em: <a href="https://www.ibge.gov.br/estatisticas/sociais/trabalho/22827-censodemografico-2022.html" target="_blank">https://www.ibge.gov.br/estatisticas/sociais/trabalho/22827-censodemografico-2022.html</a>.<br>MCTI. Ministério da Ciência, Tecnologia e Inovação. Relatório do Inventário Nacional das Emissões Antrópicas por Fontes e das Remoções por Sumidouros de Gases de Efeito Estufa do Brasil. Brasília, 2024. Disponível em: <a href="https://www.gov.br/mcti/pt-br/acompanhe-o-mcti/sirene/publicacoes/relatorios-bienais-de-transparencia-btrs/Relatorio_deInventario_NacionalNIR_2024_PORT.pdf" target="_blank">https://www.gov.br/mcti/pt-br/acompanhe-o-mcti/sirene/publicacoes/relatorios-bienais-de-transparencia-btrs/Relatorio_deInventario_NacionalNIR_2024_PORT.pdf</a><br>MMA – Ministério do Meio Ambiente. PNIA – PAINEL NACIONAL DE INDICADORES AMBIENTAIS. Indicadores Nacionais. Portal.<br>SEEG. Análise das emissões de gases de efeito estufa e suas implicações para as metas climáticas do Brasil. 2024. Disponível em: <a href="https://energiaeambiente.org.br/como-usar-o-seeg-municipios-sistema-de-estimativas-de-emissoes-e-remocoes-de-gases-de-efeito-estufa-20221011" target="_blank">https://energiaeambiente.org.br/como-usar-o-seeg-municipios-sistema-de-estimativas-de-emissoes-e-remocoes-de-gases-de-efeito-estufa-20221011</a>.</p>',
    'Emissões originadas da mudanças de uso da terra e floresta (tCO₂e)': '<p>As <strong>Emissões originadas da mudanças de uso da terra e floresta</strong> (tCO₂e) cobrem as emissões relacionadas à dinâmica de conversão de uso da terra/desmatamento e à contabilização de produtos florestais madeireiros.</p><p><strong>Resolução:</strong> Não se aplica.</p><p><strong>Unidade de medida:</strong> toneladas de CO₂ equivalente (tCO₂e), determinadas pelo fator GWP-100.</p><p><strong>Metodologia:</strong> No SEEG, aplica-se “emissão por setor” para Mudança do uso da terra e floresta, com extração de CSV municipais (até 2023). Os dados são agregados no Google Earth Engine (2016–2023) e tratados no QGIS para sintetização e mapeamento com a malha municipal do IBGE (Censo 2022).</p><p><strong>Componentes do setor:</strong></p><ul><li>Dinâmica de conversão de uso da terra/desmatamento;</li><li>Contabilização de produtos florestais madeireiros.</li></ul><p><strong>Cuidados ao analisar os dados:</strong> As estimativas dependem das séries e critérios de contabilização setorial vigentes no SEEG/MCTI e podem ser objeto de revisão.</p><p><strong>Fontes:</strong><br>IBGE. Censo Demográfico 2022: população e domicílios: primeiros resultados. 2023. Disponível em: <a href="https://www.ibge.gov.br/estatisticas/sociais/trabalho/22827-censodemografico-2022.html" target="_blank">https://www.ibge.gov.br/estatisticas/sociais/trabalho/22827-censodemografico-2022.html</a>.<br>MCTI. Ministério da Ciência, Tecnologia e Inovação. Relatório do Inventário Nacional das Emissões Antrópicas por Fontes e das Remoções por Sumidouros de Gases de Efeito Estufa do Brasil. Brasília, 2024. Disponível em: <a href="https://www.gov.br/mcti/pt-br/acompanhe-o-mcti/sirene/publicacoes/relatorios-bienais-de-transparencia-btrs/Relatorio_deInventario_NacionalNIR_2024_PORT.pdf" target="_blank">https://www.gov.br/mcti/pt-br/acompanhe-o-mcti/sirene/publicacoes/relatorios-bienais-de-transparencia-btrs/Relatorio_deInventario_NacionalNIR_2024_PORT.pdf</a><br>MMA – Ministério do Meio Ambiente. PNIA – PAINEL NACIONAL DE INDICADORES AMBIENTAIS. Indicadores Nacionais. Portal.<br>SEEG. Análise das emissões de gases de efeito estufa e suas implicações para as metas climáticas do Brasil. 2024. Disponível em: <a href="https://energiaeambiente.org.br/como-usar-o-seeg-municipios-sistema-de-estimativas-de-emissoes-e-remocoes-de-gases-de-efeito-estufa-20221011" target="_blank">https://energiaeambiente.org.br/como-usar-o-seeg-municipios-sistema-de-estimativas-de-emissoes-e-remocoes-de-gases-de-efeito-estufa-20221011</a>.</p>',
    'Emissões originadas de resíduos (tCO₂e)': '<p>As <strong>Emissões originadas de resíduos</strong> (tCO₂e) incluem as emissões provenientes do manejo e destinação de resíduos sólidos e líquidos em âmbito municipal.</p><p><strong>Resolução:</strong> Não se aplica.</p><p><strong>Unidade de medida:</strong> toneladas de CO₂ equivalente (tCO₂e), determinadas pelo fator GWP-100.</p><p><strong>Metodologia:</strong> No SEEG, usa-se o filtro “emissão por setor” para Resíduos, exportando CSV por município (até 2023). As séries são agregadas no Google Earth Engine (2016–2023) e processadas no QGIS para sintetização e mapeamento com a base vetorial de municípios do IBGE (Censo 2022).</p><p><strong>Componentes do setor:</strong></p><ul><li>Disposição de resíduos sólidos;</li><li>Tratamento biológico de resíduos sólidos;</li><li>Incineração e queima de resíduos a céu aberto;</li><li>Tratamento e despejo de águas residuárias.</li></ul><p><strong>Cuidados ao analisar os dados:</strong> As estimativas refletem as categorias e séries do SEEG; diferenças em práticas locais de manejo e reporte podem afetar a distribuição espacial das emissões.</p><p><strong>Fontes:</strong><br>IBGE. Censo Demográfico 2022: população e domicílios: primeiros resultados. 2023. Disponível em: <a href="https://www.ibge.gov.br/estatisticas/sociais/trabalho/22827-censodemografico-2022.html" target="_blank">https://www.ibge.gov.br/estatisticas/sociais/trabalho/22827-censodemografico-2022.html</a>.<br>MCTI. Ministério da Ciência, Tecnologia e Inovação. Relatório do Inventário Nacional das Emissões Antrópicas por Fontes e das Remoções por Sumidouros de Gases de Efeito Estufa do Brasil. Brasília, 2024. Disponível em: <a href="https://www.gov.br/mcti/pt-br/acompanhe-o-mcti/sirene/publicacoes/relatorios-bienais-de-transparencia-btrs/Relatorio_deInventario_NacionalNIR_2024_PORT.pdf" target="_blank">https://www.gov.br/mcti/pt-br/acompanhe-o-mcti/sirene/publicacoes/relatorios-bienais-de-transparencia-btrs/Relatorio_deInventario_NacionalNIR_2024_PORT.pdf</a><br>MMA – Ministério do Meio Ambiente. PNIA – PAINEL NACIONAL DE INDICADORES AMBIENTAIS. Indicadores Nacionais. Portal.<br>SEEG. Análise das emissões de gases de efeito estufa e suas implicações para as metas climáticas do Brasil. 2024. Disponível em: <a href="https://energiaeambiente.org.br/como-usar-o-seeg-municipios-sistema-de-estimativas-de-emissoes-e-remocoes-de-gases-de-efeito-estufa-20221011" target="_blank">https://energiaeambiente.org.br/como-usar-o-seeg-municipios-sistema-de-estimativas-de-emissoes-e-remocoes-de-gases-de-efeito-estufa-20221011</a>.</p>',

    // Panorama geral Políticas Públicas
    'Panorama dos indicadores': '<p>O <strong>Panorama dos indicadores</strong> apresenta uma visão resumida e integrada dos cinco eixos temáticos do painel de <em>Políticas Públicas</em>: <strong>Parques e Praças</strong>, <strong>Vegetação</strong>, <strong>Hidrologia</strong>, <strong>Agricultura Urbana</strong> e <strong>Emissões e Clima</strong>. Para cada eixo, são exibidos o <strong>selo UrbVerde</strong>, os <strong>objetivos estratégicos</strong>, as <strong>metas propostas</strong>, as <strong>ações necessárias</strong> e os <strong>indicadores associados</strong> que devem ser monitorados para o cumprimento dessas ações.</p><p>Esse panorama funciona como um resumo sintético para gestores e cidadãos acompanharem o avanço das políticas urbanas sustentáveis. Para acessar os dados detalhados e compreender melhor cada ação e seus respectivos indicadores, recomenda-se visitar as seções específicas de cada eixo temático na plataforma.</p>'
  };

  // Retorna a descrição específica ou um texto padrão
  return layerDescriptions[currentLayer.value] ||
      'Ops! Ainda não há informações específicas aqui. Por enquanto, clique em "Ler mais" para encontrar mais informações da camada.';
});

// URL da documentação para cada camada
const getLayerInfoUrl = computed(() => {
  const layerUrls = {
    // Clima
    'Temperatura de superfície': 'https://urbverde-educa.tawk.help/article/temperatura-de-superf%C3%ADcie-terrestre-tst',
    'Temperatura máxima de superfície':'https://urbverde-educa.tawk.help/article/temperatura-de-superf%C3%ADcie-terrestre-tst',
    'Nível de Exposição à ilha de calor':'https://urbverde-educa.tawk.help/article/coeficiente-de-ilha-de-calor',

    // Vegetação
    'Cobertura vegetal (PCV)': 'https://urbverde-educa.tawk.help/article/percentual-de-cobertura-vegetal-pcv',
    'Desigualdade sociambiental (IDSA)':'https://urbverde-educa.tawk.help/article/%C3%ADndice-de-desigualdade-socioambiental-idsa',
    'Cobertura vegetal por pixel':'https://urbverde-educa.tawk.help/article/vegeta%C3%A7%C3%A3o',
    'Vigor da vegetação (NDVI)':'https://urbverde-educa.tawk.help/article/%C3%ADndice-de-vegeta%C3%A7%C3%A3o-por-diferen%C3%A7a-normalizada-ndvi',
    'Cobertura vegetal por habitante (ICV)':'https://urbverde-educa.tawk.help/article/%C3%ADndice-de-cobertura-vegetal-icv',

    // Parques e praças
    'Distância media até as praças':'https://urbverde-educa.tawk.help/article/dist%C3%A2ncia-m%C3%A9dia-at%C3%A9-as-pra%C3%A7as',
    'Distância media até as praças (>5000m²)':'https://urbverde-educa.tawk.help/article/dist%C3%A2ncia-m%C3%A9dia-at%C3%A9-as-pra%C3%A7as',
    'Área de praças por habitante':'https://urbverde-educa.tawk.help/article/%C3%A1rea-de-pra%C3%A7as-por-habitante-m%C2%B2hab',
    'Área atendida pelas praças':'https://urbverde-educa.tawk.help/article/%C3%A1rea-atendida-pelas-pra%C3%A7as',
    'População atendida pelas praças (%)':'https://urbverde-educa.tawk.help/article/popula%C3%A7%C3%A3o-atendida-por-pra%C3%A7as',
  };

  return layerUrls[currentLayer.value] || 'https://urbverde-educa.tawk.help/category/categorias-e-camadas';
});

// Método para abrir o modal
function show() {
  refModal.value.show();
}

// Método para fechar o modal
function closeModal() {
  refModal.value.hide();
}

// Método para abrir a página de informações da camada
function openLayerInfoPage() {
  window.open(getLayerInfoUrl.value, '_blank', 'noopener,noreferrer');
}

// Expor métodos para componentes pais
defineExpose({ show, closeModal });
</script>

  <style scoped lang="scss">
  .layer-info-content {
    margin-bottom: 16px;
    color: map-get($body-text, body-color);
  }

  /* Adicione essa classe global para aplicar ao título do modal */
  :global(.layer-info-modal .modal-title) {
    white-space: pre-line !important;
  }
  </style>
