export const LAYERS_DEFAULT = [
  {
    name: "Camadas Base",
    categoria: "base",
    type: "fill",
    visible: true,
    visibleUI: false,
    colorUI: "#d4ecd5",
    zIndex: 50,
    componentName: "MunicipiosVector",
    legends: [
      {
        color: "#7c99f4",
        contour: true,
        value: "Municípios",
      },
      {
        color: "black",
        contour: true,
        value: "Setores Censitários",
      },
      {
        color: "#addd8e",
        value: "Parques e Praças",
      },
    ],
    props: {
      source: {
        generateId: true,
        type: "vector",
        tiles: [
          // https://urbverde.iau.usp.br/dados
          `https://urbverde.iau.usp.br/dados/public.geom_municipios/{z}/{x}/{y}.pbf?`,
        ],
        minzoom: 0,
        maxzoom: 22,
      },
    },
    sourceLayer: "public.geom_municipios",
  },
  {
    name: "Setores Censitários",
    categoria: "base",
    type: "fill",
    visible: true,
    visibleUI: false,
    colorUI: "#d4ecd5",
    zIndex: 50,
    componentName: "SetoresCensitariosVector",
    props: {
      source: {
        generateId: true,
        type: "vector",
        tiles: [
          `https://urbverde.iau.usp.br/dados/public.geom_setores/{z}/{x}/{y}.pbf?`,
        ],
        minzoom: 0,
        maxzoom: 22,
      },
    },
    sourceLayer: "public.geom_setores",
  },
  {
    name: "Praças e Parques",
    categoria: "base",
    type: "fill",
    visible: false,
    visibleUI: false,
    colorUI: "#d4ecd5",
    zIndex: 50,
    componentName: "PracasParquesVector",
    props: {
      source: {
        generateId: true,
        type: "vector",
        tiles: [
          `https://urbverde.iau.usp.br/dados/public.geom_pracas/{z}/{x}/{y}.pbf?`,
        ],
        minzoom: 0,
        maxzoom: 22,
      },
    },
    sourceLayer: "public.geom_pracas",
  },

  // Camadas Principais - ESTADUAL:VEGETACAO

  {
    name: "% Cobertura Vegetal (PCV)",
    categoria: "principal_vegetacao",
    type: "fill",
    visible: false,
    visibleUI: true,
    colorUI: "#d4ecd5",
    zIndex: 51,
    componentName: "PercentualCoberturaVegetal",
    opacity: 1,
  },
  {
    name: "% Cobertura Vegetal (PCV) por mesorregião",
    categoria: "/% Cobertura Vegetal (PCV)",
    type: "fill",
    visible: false,
    visibleUI: true,
    colorUI: "#d4ecd5",
    zIndex: 51,
    componentName: "VegetacaoMesorregiao",
    opacity: 1,
    legends: [
      {
        value: "0 - 0.4",
        range: true,
        color: "linear-gradient(to right top, #e3f08b, #9cda4b, #0ec406)",
      },
    ],
    paint: {
      "fill-color": [
        "interpolate",
        ["linear"],
        ["get", "b1"],
        0,
        "#e3f08b",
        0.15,
        "#9cda4b",
        0.3,
        "#0ec406",
      ],
    },
  },
  {
    name: "% Cobertura Vegetal (PCV) por microrregião",
    categoria: "/% Cobertura Vegetal (PCV)",
    type: "fill",
    visible: false,
    visibleUI: true,
    colorUI: "#d4ecd5",
    zIndex: 51,
    componentName: "VegetacaoMicrorregiao",
    opacity: 1,
    legends: [
      {
        value: "0 - 0.4",
        range: true,
        color: "linear-gradient(to right top, #e3f08b, #9cda4b, #0ec406)",
      },
    ],
    paint: {
      "fill-color": [
        "interpolate",
        ["linear"],
        ["get", "b1"],
        0,
        "#e3f08b",
        0.15,
        "#9cda4b",
        0.3,
        "#0ec406",
      ],
    },
  },

  {
    name: "Índice de Cobertura Vegetal (ICV)",
    categoria: "principal_vegetacao",
    type: "fill",
    visible: false,
    visibleUI: true,
    colorUI: "#d4ecd5",
    zIndex: 51,
    componentName: "IndiceCoberturaVegetal",
    opacity: 1,
    // essa propriedade precisa ser iniciada com o mesmo valor da propriedade 'visible'
    legends: [],
    paint: {},
  },
  {
    name: "Índice de Cobertura Vegetal (ICV) por mesorregião",
    categoria: "/Índice de Cobertura Vegetal (ICV)",
    type: "fill",
    visible: false,
    visibleUI: true,
    colorUI: "#d4ecd5",
    zIndex: 51,
    componentName: "VegetacaoMesorregiao",
    opacity: 1,
    legends: [
      {
        value: "0 - 0.4",
        range: true,
        color: "linear-gradient(to right top, #e3f08b, #6ccf2d, #088703)",
      },
    ],
    paint: {
      "fill-color": [
        "interpolate",
        ["linear"],
        ["get", "b2"],
        700,
        "#e3f08b",
        1400,
        "#c2e56a",
        2100,
        "#9cda4b",
        2800,
        "#6ccf2d",
        3500,
        "#0ec406",
        4200,
        "#088703",
      ],
    },
  },

  {
    name: "Índice de Cobertura Vegetal (ICV) por microrregião",
    categoria: "/Índice de Cobertura Vegetal (ICV)",
    type: "fill",
    visible: false,
    visibleUI: true,
    colorUI: "#d4ecd5",
    zIndex: 51,
    componentName: "VegetacaoMicrorregiao",
    opacity: 1,
    legends: [
      {
        value: "0 - 0.4",
        range: true,
        color: "linear-gradient(to right top, #e3f08b, #6ccf2d, #088703)",
      },
    ],
    paint: {
      "fill-color": [
        "interpolate",
        ["linear"],
        ["get", "b2"],
        700,
        "#e3f08b",
        1400,
        "#c2e56a",
        2100,
        "#9cda4b",
        2800,
        "#6ccf2d",
        3500,
        "#0ec406",
        4200,
        "#088703",
      ],
    },
  },
  {
    name: "Índice de Desenvolvimento Socioambiental (IDSA)",
    categoria: "principal_vegetacao",
    type: "fill",
    visible: false,
    visibleUI: true,
    colorUI: "#d4ecd5",
    zIndex: 51,
    componentName: "IndiceDesenvolvimentoSocioambiental",
    opacity: 1,
  },
  {
    name: "Índice de Desenvolvimento Socioambiental (IDSA) por mesorregião",
    categoria: "/Índice de Desenvolvimento Socioambiental (IDSA)",
    type: "fill",
    visible: false,
    visibleUI: true,
    colorUI: "#d4ecd5",
    zIndex: 51,
    componentName: "VegetacaoMesorregiao",
    opacity: 1,
    legends: [
      {
        value: "0 - 1",
        range: true,
        color: "linear-gradient(to right top, #d53e4f, #a264b3, #3288bd)",
      },
    ],

    paint: {
      "fill-color": [
        "interpolate",
        ["linear"],
        ["get", "b3"],
        0,
        "#d53e4f",
        0.5,
        "#a264b3",
        1,
        "#3288bd",
      ],
    },
  },
  {
    name: "Índice de Desenvolvimento Socioambiental (IDSA) por microrregião",
    categoria: "/Índice de Desenvolvimento Socioambiental (IDSA)",
    type: "fill",
    visible: false,
    visibleUI: true,
    colorUI: "#d4ecd5",
    zIndex: 51,
    componentName: "VegetacaoMicrorregiao",
    opacity: 1,
    legends: [
      {
        value: "0 - 1",
        range: true,
        color: "linear-gradient(to right top, #d53e4f, #a264b3, #3288bd)",
      },
    ],

    paint: {
      "fill-color": [
        "interpolate",
        ["linear"],
        ["get", "b3"],
        0,
        "#d53e4f",
        0.5,
        "#a264b3",
        1,
        "#3288bd",
      ],
    },
  },
  // Camadas Principais - PRACAS

  {
    name: "Acesso população atendida pelas praças",
    categoria: "principal_pracas",
    type: "fill",
    visible: false,
    visibleUI: true,
    colorUI: "#d4ecd5",
    zIndex: 51,
    componentName: "AcessoPopulacaoAtendidasPelasPracas",
    opacity: 1,
    legends: [{}],
    paint: {},
  },
  {
    name: "Acesso população atendida pelas praças por mesorregião",
    categoria: "/Acesso população atendida pelas praças",
    type: "fill",
    visible: false,
    visibleUI: true,
    colorUI: "#d4ecd5",
    zIndex: 51,
    componentName: "ParquesMesorregiao",
    opacity: 1,
    legends: [
      {
        range: true,
        color: "linear-gradient(to right, #d73027, #1a9850)",
        value: `0.06 - 0.20`,
      },
    ],
    paint: {
      "fill-color": [
        "interpolate",
        ["linear"],
        ["get", "a1"],
        0.06,
        "#d73027",
        0.2,
        "#1a9850",
      ],
    },
  },
  {
    name: "Acesso população atendida pelas praças por microrregião",
    categoria: "/Acesso população atendida pelas praças",
    type: "fill",
    visible: false,
    visibleUI: true,
    colorUI: "#d4ecd5",
    zIndex: 51,
    componentName: "ParquesMicrorregiao",
    opacity: 1,
    legends: [
      {
        range: true,
        color:
          "linear-gradient(to right, #d73027, #fc8d59, #fee08b, #ffffbf, #d9ef8b, #91cf60, #1a9850)",
        value: `0.05 - 0.28`,
      },
    ],
    paint: {
      "fill-color": [
        "interpolate",
        ["linear"],
        ["get", "a1"],
        0.05,
        "#d73027",
        0.07,
        "#fc8d59",
        0.09,
        "#fee08b",
        0.13,
        "#ffffbf",
        0.19,
        "#d9ef8b",
        0.21,
        "#91cf60",
        0.28,
        "#1a9850",
      ],
    },
  },

  {
    name: "M² de praças por Habitante",
    categoria: "principal_pracas",
    type: "fill",
    visible: false,
    visibleUI: true,
    colorUI: "#d4ecd5",
    zIndex: 51,
    componentName: "PracasPorHabitante",
    opacity: 1,
  },

  {
    name: "M² de praças por Habitante por mesorregião",
    categoria: "/M² de praças por Habitante",
    type: "fill",
    visible: false,
    visibleUI: true,
    colorUI: "#d4ecd5",
    zIndex: 51,
    componentName: "ParquesMesorregiao",
    opacity: 1,
    legends: [
      {
        value: "3010 - 14.803.000",
        range: true,
        color: "linear-gradient(to right, #EC6060, #6E4DE7",
      },
    ],
    paint: {
      "fill-color": [
        "interpolate",
        ["linear"],
        ["get", "a2"],
        3010,
        "#EC6060",
        14803000,
        "#6E4DE7",
      ],
    },
  },
  {
    name: "M² de praças por Habitante por microrregião",
    categoria: "/M² de praças por Habitante",
    type: "fill",
    visible: false,
    visibleUI: true,
    colorUI: "#d4ecd5",
    zIndex: 51,
    componentName: "ParquesMicrorregiao",
    opacity: 1,
    legends: [
      {
        value: "1500 - 28.968.281",
        range: true,
        color: "linear-gradient(to right, #EC6060, #6E4DE7",
      },
    ],
    paint: {
      "fill-color": [
        "interpolate",
        ["linear"],
        ["get", "a2"],
        1500,
        "#EC6060",
        28968281,
        "#6E4DE7",
      ],
    },
  },

  {
    name: "% de área ocupada pelos buffers",
    categoria: "principal_pracas",
    type: "fill",
    visible: false,
    visibleUI: true,
    colorUI: "#d4ecd5",
    zIndex: 51,
    componentName: "AreasOcupadasBuffers",
    opacity: 1,
  },

  {
    name: "% de área ocupada pelos buffers municipais por Mesorregião",
    categoria: "/% de área ocupada pelos buffers",
    type: "fill",
    visible: false,
    visibleUI: true,
    colorUI: "#d4ecd5",
    zIndex: 51,
    componentName: "ParquesMesorregiao",
    opacity: 1,
    legends: [
      {
        value: "0.605 - 0.700",
        range: true,
        color: "linear-gradient(to right, #E1FF9D, #3700FF)",
      },
    ],
    paint: {
      "fill-color": [
        "interpolate",
        ["linear"],
        ["get", "a3"],
        0.5,
        "#E1FF9D",
        0.7,
        "#16C02C",
      ],
    },
  },
  {
    name: "% de área ocupada pelos buffers municipais por microrregião",
    categoria: "/% de área ocupada pelos buffers",
    type: "fill",
    visible: false,
    visibleUI: true,
    colorUI: "#d4ecd5",
    zIndex: 51,
    componentName: "ParquesMicrorregiao",
    opacity: 1,
    legends: [
      {
        value: "0.5 - 0.8",
        range: true,
        color: "linear-gradient(to right, #E1FF9D, #3700FF)",
      },
    ],
    paint: {
      "fill-color": [
        "interpolate",
        ["linear"],
        ["get", "a3"],
        0.5,
        "#E1FF9D",
        0.8,
        "#3700FF",
      ],
    },
  },

  {
    name: "Distribuição espacial das praças",
    categoria: "principal_pracas",
    type: "fill",
    visible: false,
    visibleUI: true,
    colorUI: "#d4ecd5",
    zIndex: 51,
    componentName: "DistribuicaoEspacial",
    opacity: 1,
  },
  {
    name: "Distribuição espacial das praças por Mesorregião",
    categoria: "/Distribuição espacial das praças",
    type: "fill",
    visible: false,
    visibleUI: true,
    colorUI: "#d4ecd5",
    zIndex: 51,
    componentName: "ParquesMesorregiao",
    opacity: 1,

    legends: [
      {
        value: "0 - 0.3",
        range: true,
        color: "linear-gradient(to right, #E1FF9D, #3700FF)",
      },
    ],
    paint: {
      "fill-color": [
        "interpolate",
        ["linear"],
        ["get", "a4"],
        0,
        "#E1FF9D",
        0.3,
        "#3700FF",
      ],
    },
  },
  {
    name: "Distribuição espacial das praças por microrregião",
    categoria: "/Distribuição espacial das praças",
    type: "fill",
    visible: false,
    visibleUI: true,
    colorUI: "#d4ecd5",
    zIndex: 51,
    componentName: "ParquesMicrorregiao",
    opacity: 1,
    legends: [
      {
        value: "0 - 0.3",
        range: true,
        color: "linear-gradient(to right, #E1FF9D, #3700FF)",
      },
    ],
    paint: {
      "fill-color": [
        "interpolate",
        ["linear"],
        ["get", "a4"],
        0,
        "#E1FF9D",
        0.3,
        "#3700FF",
      ],
    },
  },

  {
    name: "Produto Interno Bruto",
    categoria: "aux_pracas",
    type: "fill",
    visible: false,
    visibleUI: true,
    colorUI: "#d4ecd5",
    zIndex: 51,
    componentName: "Renda",
    opacity: 1,
  },

  {
    name: "Coeficiente de Gini",
    categoria: "aux_pracas",
    type: "fill",
    visible: false,
    visibleUI: true,
    colorUI: "#d4ecd5",
    zIndex: 51,
    componentName: "RegioesLayer",
    opacity: 1,
    sourceLayer: "public.geodata_pracas_por_municipio_2021",
    props: {
      source: {
        generateId: true,
        type: "vector",
        tiles: [
          `https://urbverde.iau.usp.br/dados/public.geodata_pracas_por_municipio_2021/{z}/{x}/{y}.pbf?`,
        ],
        minzoom: 0,
        maxzoom: 22,
      },
    },

    legends: [
      {
        value: "0.33 - 0.68",
        range: true,
        color: "linear-gradient(to right, #E14949, #3700FF",
      },
    ],
    paint: {
      "fill-color": [
        "interpolate",
        ["linear"],
        ["get", "gini"],
        0.3339,
        "#E14949",
        0.6858,
        "#3700FF",
      ],
    },
  },
  {
    name: "Índice de Desenvolvimento Humano",
    categoria: "aux_pracas",
    type: "fill",
    visible: false,
    visibleUI: true,
    colorUI: "#d4ecd5",
    zIndex: 51,
    componentName: "RegioesLayer",
    opacity: 1,
    sourceLayer: "public.geodata_pracas_por_municipio_2021",
    props: {
      source: {
        generateId: true,
        type: "vector",
        tiles: [
          `https://urbverde.iau.usp.br/dados/public.geodata_pracas_por_municipio_2021/{z}/{x}/{y}.pbf?`,
        ],
        minzoom: 0,
        maxzoom: 22,
      },
    },

    legends: [
      {
        range: true,
        color: "linear-gradient(to right, #f63939, #6c3df2",
        value: "0.639 - 0.862",
      },
    ],
    paint: {
      "fill-color": [
        "interpolate",
        ["linear"],
        ["get", "idh"],
        0.639,
        "#f63939",
        0.862,
        "#6c3df2",
      ],
    },
  },

  {
    name: "Mancha Urbana",
    categoria: "aux_pracas",
    type: "raster",
    visible: false,
    visibleUI: true,
    colorUI: "#d4ecd5",
    zIndex: 1,
    componentName: "ManchaUrbana",
    opacity: 1,
    props: {
      source: {
        type: "raster",
        generateId: true,
        tiles: [
          `https://urbverde.iau.usp.br/geoserver/urbverde/wms?service=WMS&version=1.1.0&request=GetMap&layers=urbverde%3ANew-Mancha-Urbana&bbox={bbox-epsg-3857}&transparent=true&width=768&height=478&srs=EPSG%3A3857&styles=&format=image%2Fpng`,
        ],
      },
    },
  },

  {
    name: "Temperatura - intraurbano",
    categoria: "aux_pracas_intraurbano",
    type: "raster",
    visible: false,
    visibleUI: true,
    colorUI: "#d4ecd5",
    zIndex: 52,
    componentName: "AuxTempIntraurb",
    props: {
      source: {},
    },
  },

  {
    name: "Renda",
    categoria: "aux_pracas_intraurbano",
    type: "fill",
    visible: false,
    visibleUI: true,
    colorUI: "#d4ecd5",
    zIndex: 51,
    componentName: "Renda",
    opacity: 1,
    legends: [
      {
        range: true,
        value: "0 - 10 %",
        color:
          "linear-gradient(to right, #f63939, #fc3f74, #ee5aa7, #d177ce, #ad90e3, #9c91e9, #8792ed, #6d93f1, #6182f6, #5c6ff8, #6159f7, #6c3df2)",
      },
    ],
    paint: {},
  },

  {
    name: "Parques e Praças",
    categoria: "aux_pracas_intraurbano",
    type: "fill",
    visible: false,
    visibleUI: true,
    colorUI: "#d4ecd5",
    zIndex: 50,
    componentName: "PracasParquesVector",
    props: {
      source: {
        generateId: true,
        type: "vector",
        tiles: [
          `https://urbverde.iau.usp.br/dados/public.geom_pracas/{z}/{x}/{y}.pbf?`,
        ],
        minzoom: 0,
        maxzoom: 22,
      },
    },
    sourceLayer: "public.geom_pracas",
  },

  {
    name: "Buffer de 400m em torno das praças",
    categoria: "aux_pracas_intraurbano",
    type: "fill",
    visible: false,
    visibleUI: true,
    colorUI: "#d4ecd5",
    zIndex: 52,
    componentName: "Buffer400m",
    opacity: 0.5,
    legends: [
      {
        color: "#FF6F91",
        value: "Área do buffer",
      },
    ],

    props: {
      source: {
        generateId: true,
        type: "vector",
        tiles: [
          `https://urbverde.iau.usp.br/dados/public.geom_buffer_400m_municipios/{z}/{x}/{y}.pbf?`,
        ],
        minzoom: 0,
        maxzoom: 22,
      },
    },
    sourceLayer: "public.geom_buffer_400m_municipios",
  },

  {
    name: "Vegetação",
    categoria: "aux_veg",
    type: "raster",
    visible: false,
    visibleUI: true,
    colorUI: "#d4ecd5",
    zIndex: 51,
    componentName: "VegetacaoRaster",
    props: {
      source: {},
    },
    legends: [
      {
        range: true,
        color:
          "linear-gradient(to right, #ff4903, #ff7100, #ff9300, #ffb200, #ffd000, #edd500, #dadb00, #c5df00, #9bcc05, #73b90f, #49a416, #10901b)",
        value: `0 - 100%`,
      },
    ],
  },

  {
    name: "Anual NDVI",
    categoria: "aux_veg",
    type: "raster",
    visible: false,
    visibleUI: true,
    colorUI: "#d4ecd5",
    zIndex: 52,
    componentName: "NdviRaster",
    props: {
      source: {},
    },
    legends: [
      {
        range: true,
        color:
          "linear-gradient(to right, #addd8e, #78c679, #41ab5d, #238443, #006837, #004529)",
        value: `0 - 100%`,
      },
    ],
  },
  {
    name: "ISs",
    categoria: "aux_veg_estadual",
    type: "fill",
    visible: false,
    visibleUI: true,
    colorUI: "#d4ecd5",
    zIndex: 51,
    componentName: "ISs",
    opacity: 1,
  },
  {
    name: "ISi",
    categoria: "aux_veg_estadual",
    type: "fill",
    visible: false,
    visibleUI: true,
    colorUI: "#d4ecd5",
    zIndex: 51,
    componentName: "ISi",
    opacity: 1,
  },
  {
    name: "ISd",
    categoria: "aux_veg_estadual",
    type: "fill",
    visible: false,
    visibleUI: true,
    colorUI: "#d4ecd5",
    zIndex: 51,
    componentName: "ISd",
    opacity: 1,
  },

  {
    name: "Coeficiente de Ilha de Calor",
    categoria: "principal_temperatura",
    type: "fill",
    visible: false,
    visibleUI: true,
    colorUI: "#d4ecd5",
    zIndex: 51,
    componentName: "CoeficienteIlhaCalor",
    opacity: 1,
  },

  {
    name: "Coeficiente de Ilha de Calor por Mesorregião",
    categoria: "/Coeficiente de Ilha de Calor",
    type: "fill",
    visible: false,
    visibleUI: true,
    colorUI: "#d4ecd5",
    zIndex: 51,
    componentName: "TemperaturaMesorregiao",
    opacity: 1,
    sourceLayer: "public.geodata_vegetacao_por_mesorregiao_2016",
    legends: [
      {
        value: "0.06 - 4.73",
        range: true,
        color: "linear-gradient(to right, #3288bd, #d53e4f)",
      },
    ],
    paint: {
      "fill-color": [
        "interpolate",
        ["linear"],
        ["get", "c1"],
        0.06,
        ["to-color", "#ffffe5"],
        4.73,
        ["to-color", "#41ab5d"],
      ],
    },
  },
  {
    name: "Coeficiente de Ilha de Calor por microrregião",
    categoria: "/Coeficiente de Ilha de Calor",
    type: "fill",
    visible: false,
    visibleUI: true,
    colorUI: "#d4ecd5",
    zIndex: 51,
    componentName: "TemperaturaMicrorregiao",
    opacity: 1,
    legends: [
      {
        value: "0.02 - 16",
        range: true,
        color: "linear-gradient(to right, #3288bd, #d53e4f)",
      },
    ],
    paint: {
      "fill-color": [
        "interpolate",
        ["linear"],
        ["get", "c1"],
        0.02,
        ["to-color", "#3288bd"],
        16,
        ["to-color", "#d53e4f"],
      ],
    },
  },

  {
    name: "Temperatura Média de Superfície (TMS)",
    categoria: "principal_temperatura",
    type: "fill",
    visible: false,
    visibleUI: true,
    colorUI: "#d4ecd5",
    zIndex: 51,
    componentName: "TemperaturaMediaSuperficie",
    opacity: 1,
  },
  {
    name: "TMS por Mesorregião",
    categoria: "/Temperatura Média de Superfície (TMS)",
    type: "fill",
    visible: false,
    visibleUI: true,
    colorUI: "#d4ecd5",
    zIndex: 51,
    componentName: "TemperaturaMesorregiao",
    opacity: 1,
    legends: [
      {
        value: "0 - 100 ºC",
        range: true,
        color: "linear-gradient(to right, #3288bd, #d53e4f)",
      },
    ],
    paint: {
      "fill-color": [
        "interpolate",
        ["linear"],
        ["get", "c2"],
        22,
        ["to-color", "#3288bd"],
        34,
        ["to-color", "#d53e4f"],
      ],
    },
  },
  {
    name: "TMS por microrregião",
    categoria: "/Temperatura Média de Superfície (TMS)",
    type: "fill",
    visible: false,
    visibleUI: true,
    colorUI: "#d4ecd5",
    zIndex: 51,
    componentName: "TemperaturaMicrorregiao",
    opacity: 1,
    legends: [
      {
        value: "0 - 100 ºC",
        range: true,
        color: "linear-gradient(to right, #3288bd, #d53e4f)",
      },
    ],
    paint: {
      "fill-color": [
        "interpolate",
        ["linear"],
        ["get", "c2"],
        0.02,
        ["to-color", "#3288bd"],
        34.17,
        ["to-color", "#d53e4f"],
      ],
    },
  },
  {
    name: "Temperatura Máxima de Superfície",
    categoria: "principal_temperatura",
    type: "fill",
    visible: false,
    visibleUI: true,
    colorUI: "#d4ecd5",
    zIndex: 51,
    componentName: "TemperaturaMaximaSuperficie",
    opacity: 1,
  },
  {
    name: "TS máxima por Mesorregião",
    categoria: "/Temperatura Máxima de Superfície",
    type: "fill",
    visible: false,
    visibleUI: true,
    colorUI: "#d4ecd5",
    zIndex: 51,
    componentName: "TemperaturaMesorregiao",
    opacity: 1,
    legends: [
      {
        value: "0 - 100 ºC",
        range: true,
        color: "linear-gradient(to right, #3288bd, #d53e4f)",
      },
    ],
    paint: {
      "fill-color": [
        "interpolate",
        ["linear"],
        ["get", "c2"],
        33,
        ["to-color", "#3288bd"],
        40,
        ["to-color", "#d53e4f"],
      ],
    },
  },
  {
    name: "TS máxima por microrregião",
    categoria: "/Temperatura Máxima de Superfície",
    type: "fill",
    visible: false,
    visibleUI: true,
    colorUI: "#d4ecd5",
    zIndex: 51,
    componentName: "TemperaturaMicrorregiao",
    opacity: 1,
    legends: [
      {
        value: "0 - 100 ºC",
        range: true,
        color: "linear-gradient(to right, #3288bd, #d53e4f)",
      },
    ],
    paint: {
      "fill-color": [
        "interpolate",
        ["linear"],
        ["get", "c3"],
        30.88,
        ["to-color", "#3288bd"],
        44.7,
        ["to-color", "#d53e4f"],
      ],
    },
  },

  {
    name: "Temperatura - microclimas",
    categoria: "aux_temperatura_intraurbano",
    type: "raster",
    visible: false,
    visibleUI: true,
    colorUI: "#d4ecd5",
    zIndex: 1,
    componentName: "TemperaturaRaster",
    props: {
      source: {},
    },
  },

  {
    name: "Temperatura",
    categoria: "aux_temperatura",
    type: "raster",
    visible: false,
    visibleUI: true,
    colorUI: "#d4ecd5",
    zIndex: 1,
    componentName: "TemperaturaRaster",
    props: {
      source: {},
    },
  },

  // {
  //   name: "Teste Martin",
  //   categoria: "",
  //   type: "circle",
  //   visible: true,
  //   visibleUI: false,
  //   colorUI: "#d4ecd5",
  //   zIndex: 51,
  //   componentName: "PracasParquesDataLayer",
  //   props: {
  //     source: {
  //       generateId: true,
  //       type: "vector",
  //       url: "http://localhost:3000/public.points2.json?limit=100",
  //     },
  //   },
  //   sourceLayer: "public.points2",
  //   paint: {
  //     "circle-color": "#8481ff",
  //   },
  // },
];
