name: Deploy UI to Production
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22.12.0'
        
    - name: Install Dependencies
      run: npm ci
      
    - name: Build Project
      run: npm run build
      
    - name: Deploy to SSH Server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.PRODUCTION_HOST }}
        username: ${{ secrets.PRODUCTION_USER }}
        password: ${{ secrets.PRODUCTION_PASSWORD }}
        port: ${{ secrets.PRODUCTION_PORT }}
        source: "dist/"
        target: "/home/${{ secrets.PRODUCTION_USER }}/sphere-api-stack/"
        strip_components: 0
        
    - name: Setup on Server
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.PRODUCTION_HOST }}
        username: ${{ secrets.PRODUCTION_USER }}
        password: ${{ secrets.PRODUCTION_PASSWORD }}
        port: ${{ secrets.PRODUCTION_PORT }}
        script: |
          # Create a timestamp for this deployment
          TIMESTAMP=$(date +%Y%m%d-%H%M%S)
          
          # Save the deployment timestamp
          echo "$TIMESTAMP" > /home/${{ secrets.PRODUCTION_USER }}/sphere-api-stack/urbverde-ui-version.txt
          
          # Reload Nginx configuration using Docker
          docker exec nginx_urbverde nginx -s reload
